In [94]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime as dt
import plotly
import plotly.graph_objs as go
import os

import time

In [3]:
capital = 1000000
transaction_percent = 1/1000

In [4]:
data_adj = pd.read_csv("1-sp500_adj_price.csv")

In [7]:
data_adj

         datadate   tic  adj_price
0        19900102  ADCT   4.074244
1        19900103  ADCT   4.046900
2        19900104  ADCT   3.964869
3        19900105  ADCT   3.992212
4        19900108  ADCT   3.937525
5        19900109  ADCT   3.910181
6        19900110  ADCT   3.910181
7        19900111  ADCT   3.992212
8        19900112  ADCT   3.910181
9        19900115  ADCT   3.910181
10       19900116  ADCT   3.964869
11       19900117  ADCT   3.964869
12       19900118  ADCT   3.937525
13       19900119  ADCT   3.882837
14       19900122  ADCT   3.882837
15       19900123  ADCT   3.937525
16       19900124  ADCT   3.910181
17       19900125  ADCT   3.992212
18       19900126  ADCT   3.937525
19       19900129  ADCT   3.882837
20       19900130  ADCT   3.828149
21       19900131  ADCT   3.828149
22       19900201  ADCT   3.800805
23       19900202  ADCT   3.992212
24       19900205  ADCT   3.937525
25       19900206  ADCT   4.128932
26       19900207  ADCT   4.429715
27       19900208  ADCT   4.539091
28       19900209  ADCT   4.484403
29       19900212  ADCT   4.457059
...           ...   ...        ...
6438934  20170921  ALLE  83.470000
6438935  20170922  ALLE  84.550000
6438936  20170925  ALLE  84.500000
6438937  20170926  ALLE  85.350000
6438938  20170927  ALLE  85.330000
6438939  20170928  ALLE  85.760000
6438940  20170929  ALLE  86.470000
6438941  20171002  ALLE  86.530000
6438942  20171003  ALLE  87.470000
6438943  20171004  ALLE  86.730000
6438944  20171005  ALLE  87.070000
6438945  20171006  ALLE  87.190000
6438946  20171009  ALLE  87.620000
6438947  20171010  ALLE  87.810000
6438948  20171011  ALLE  88.150000
6438949  20171012  ALLE  89.560000
6438950  20171013  ALLE  88.300000
6438951  20171016  ALLE  88.140000
6438952  20171017  ALLE  87.000000
6438953  20171018  ALLE  87.600000
6438954  20171019  ALLE  87.740000
6438955  20171020  ALLE  88.020000
6438956  20171023  ALLE  87.310000
6438957  20171024  ALLE  88.480000
6438958  20171025  ALLE  86.490000
6438959  20171026  ALLE  80.700000
6438960  20171027  ALLE  80.290000
6438961  20171030  ALLE  81.970000
6438962  20171031  ALLE  83.390000
6438963  20171101  ALLE  82.730000

[6438964 rows x 3 columns]

In [6]:
#delete extra column
del data_adj['Unnamed: 0']

# Data type manipulate

Python also includes a data type for sets. 
A set is an unordered collection with no duplicate elements. 
Basic uses include membership testing and eliminating duplicate entries. 
Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

In [29]:
#convert to list from pandas.core.series.Series

#use set to get unique values
daily = list(set(data_adj['datadate']))
#daily = list(set(data_adj['datadate']))
#sort it
daily.sort()
print(type(data_adj['datadate']),type(daily))

<class 'pandas.core.series.Series'> <class 'list'>

In [27]:
daily

[19900102,
 19900103,
 19900104,
 19900105,
 19900108,
 19900109,
 19900110,
 19900111,
 19900112,
 19900115,
 19900116,
 19900117,
 19900118,
 19900119,
 19900122,
 19900123,
 19900124,
 19900125,
 19900126,
 19900129,
 19900130,
 19900131,
 19900201,
 19900202,
 19900205,
 19900206,
 19900207,
 19900208,
 19900209,
 19900212,
 19900213,
 19900214,
 19900215,
 19900216,
 19900219,
 19900220,
 19900221,
 19900222,
 19900223,
 19900226,
 19900227,
 19900228,
 19900301,
 19900302,
 19900305,
 19900306,
 19900307,
 19900308,
 19900309,
 19900312,
 19900313,
 19900314,
 19900315,
 19900316,
 19900319,
 19900320,
 19900321,
 19900322,
 19900323,
 19900326,
 19900327,
 19900328,
 19900329,
 19900330,
 19900402,
 19900403,
 19900404,
 19900405,
 19900406,
 19900409,
 19900410,
 19900411,
 19900412,
 19900416,
 19900417,
 19900418,
 19900419,
 19900420,
 19900423,
 19900424,
 19900425,
 19900426,
 19900427,
 19900430,
 19900501,
 19900502,
 19900503,
 19900504,
 19900507,
 19900508,
 19900509,
 19900510,
 19900511,
 19900514,
 19900515,
 19900516,
 19900517,
 19900518,
 19900521,
 19900522,
 19900523,
 19900524,
 19900525,
 19900528,
 19900529,
 19900530,
 19900531,
 19900601,
 19900604,
 19900605,
 19900606,
 19900607,
 19900608,
 19900611,
 19900612,
 19900613,
 19900614,
 19900615,
 19900618,
 19900619,
 19900620,
 19900621,
 19900622,
 19900625,
 19900626,
 19900627,
 19900628,
 19900629,
 19900702,
 19900703,
 19900704,
 19900705,
 19900706,
 19900709,
 19900710,
 19900711,
 19900712,
 19900713,
 19900716,
 19900717,
 19900718,
 19900719,
 19900720,
 19900723,
 19900724,
 19900725,
 19900726,
 19900727,
 19900730,
 19900731,
 19900801,
 19900802,
 19900803,
 19900806,
 19900807,
 19900808,
 19900809,
 19900810,
 19900813,
 19900814,
 19900815,
 19900816,
 19900817,
 19900820,
 19900821,
 19900822,
 19900823,
 19900824,
 19900827,
 19900828,
 19900829,
 19900830,
 19900831,
 19900904,
 19900905,
 19900906,
 19900907,
 19900910,
 19900911,
 19900912,
 19900913,
 19900914,
 19900917,
 19900918,
 19900919,
 19900920,
 19900921,
 19900924,
 19900925,
 19900926,
 19900927,
 19900928,
 19901001,
 19901002,
 19901003,
 19901004,
 19901005,
 19901008,
 19901009,
 19901010,
 19901011,
 19901012,
 19901015,
 19901016,
 19901017,
 19901018,
 19901019,
 19901022,
 19901023,
 19901024,
 19901025,
 19901026,
 19901029,
 19901030,
 19901031,
 19901101,
 19901102,
 19901105,
 19901106,
 19901107,
 19901108,
 19901109,
 19901112,
 19901113,
 19901114,
 19901115,
 19901116,
 19901119,
 19901120,
 19901121,
 19901122,
 19901123,
 19901126,
 19901127,
 19901128,
 19901129,
 19901130,
 19901203,
 19901204,
 19901205,
 19901206,
 19901207,
 19901210,
 19901211,
 19901212,
 19901213,
 19901214,
 19901217,
 19901218,
 19901219,
 19901220,
 19901221,
 19901224,
 19901226,
 19901227,
 19901228,
 19901231,
 19910102,
 19910103,
 19910104,
 19910107,
 19910108,
 19910109,
 19910110,
 19910111,
 19910114,
 19910115,
 19910116,
 19910117,
 19910118,
 19910121,
 19910122,
 19910123,
 19910124,
 19910125,
 19910128,
 19910129,
 19910130,
 19910131,
 19910201,
 19910204,
 19910205,
 19910206,
 19910207,
 19910208,
 19910211,
 19910212,
 19910213,
 19910214,
 19910215,
 19910218,
 19910219,
 19910220,
 19910221,
 19910222,
 19910225,
 19910226,
 19910227,
 19910228,
 19910301,
 19910304,
 19910305,
 19910306,
 19910307,
 19910308,
 19910311,
 19910312,
 19910313,
 19910314,
 19910315,
 19910318,
 19910319,
 19910320,
 19910321,
 19910322,
 19910325,
 19910326,
 19910327,
 19910328,
 19910401,
 19910402,
 19910403,
 19910404,
 19910405,
 19910408,
 19910409,
 19910410,
 19910411,
 19910412,
 19910415,
 19910416,
 19910417,
 19910418,
 19910419,
 19910422,
 19910423,
 19910424,
 19910425,
 19910426,
 19910429,
 19910430,
 19910501,
 19910502,
 19910503,
 19910506,
 19910507,
 19910508,
 19910509,
 19910510,
 19910513,
 19910514,
 19910515,
 19910516,
 19910517,
 19910520,
 19910521,
 19910522,
 19910523,
 19910524,
 19910527,
 19910528,
 19910529,
 19910530,
 19910531,
 19910603,
 19910604,
 19910605,
 19910606,
 19910607,
 19910610,
 19910611,
 19910612,
 19910613,
 19910614,
 19910617,
 19910618,
 19910619,
 19910620,
 19910621,
 19910624,
 19910625,
 19910626,
 19910627,
 19910628,
 19910701,
 19910702,
 19910703,
 19910704,
 19910705,
 19910708,
 19910709,
 19910710,
 19910711,
 19910712,
 19910715,
 19910716,
 19910717,
 19910718,
 19910719,
 19910722,
 19910723,
 19910724,
 19910725,
 19910726,
 19910729,
 19910730,
 19910731,
 19910801,
 19910802,
 19910805,
 19910806,
 19910807,
 19910808,
 19910809,
 19910812,
 19910813,
 19910814,
 19910815,
 19910816,
 19910819,
 19910820,
 19910821,
 19910822,
 19910823,
 19910826,
 19910827,
 19910828,
 19910829,
 19910830,
 19910903,
 19910904,
 19910905,
 19910906,
 19910909,
 19910910,
 19910911,
 19910912,
 19910913,
 19910916,
 19910917,
 19910918,
 19910919,
 19910920,
 19910923,
 19910924,
 19910925,
 19910926,
 19910927,
 19910930,
 19911001,
 19911002,
 19911003,
 19911004,
 19911007,
 19911008,
 19911009,
 19911010,
 19911011,
 19911014,
 19911015,
 19911016,
 19911017,
 19911018,
 19911021,
 19911022,
 19911023,
 19911024,
 19911025,
 19911028,
 19911029,
 19911030,
 19911031,
 19911101,
 19911104,
 19911105,
 19911106,
 19911107,
 19911108,
 19911111,
 19911112,
 19911113,
 19911114,
 19911115,
 19911118,
 19911119,
 19911120,
 19911121,
 19911122,
 19911125,
 19911126,
 19911127,
 19911128,
 19911129,
 19911202,
 19911203,
 19911204,
 19911205,
 19911206,
 19911209,
 19911210,
 19911211,
 19911212,
 19911213,
 19911216,
 19911217,
 19911218,
 19911219,
 19911220,
 19911223,
 19911224,
 19911226,
 19911227,
 19911230,
 19911231,
 19920102,
 19920103,
 19920106,
 19920107,
 19920108,
 19920109,
 19920110,
 19920113,
 19920114,
 19920115,
 19920116,
 19920117,
 19920120,
 19920121,
 19920122,
 19920123,
 19920124,
 19920127,
 19920128,
 19920129,
 19920130,
 19920131,
 19920203,
 19920204,
 19920205,
 19920206,
 19920207,
 19920210,
 19920211,
 19920212,
 19920213,
 19920214,
 19920217,
 19920218,
 19920219,
 19920220,
 19920221,
 19920224,
 19920225,
 19920226,
 19920227,
 19920228,
 19920302,
 19920303,
 19920304,
 19920305,
 19920306,
 19920309,
 19920310,
 19920311,
 19920312,
 19920313,
 19920316,
 19920317,
 19920318,
 19920319,
 19920320,
 19920323,
 19920324,
 19920325,
 19920326,
 19920327,
 19920330,
 19920331,
 19920401,
 19920402,
 19920403,
 19920406,
 19920407,
 19920408,
 19920409,
 19920410,
 19920413,
 19920414,
 19920415,
 19920416,
 19920420,
 19920421,
 19920422,
 19920423,
 19920424,
 19920427,
 19920428,
 19920429,
 19920430,
 19920501,
 19920504,
 19920505,
 19920506,
 19920507,
 19920508,
 19920511,
 19920512,
 19920513,
 19920514,
 19920515,
 19920518,
 19920519,
 19920520,
 19920521,
 19920522,
 19920525,
 19920526,
 19920527,
 19920528,
 19920529,
 19920601,
 19920602,
 19920603,
 19920604,
 19920605,
 19920608,
 19920609,
 19920610,
 19920611,
 19920612,
 19920615,
 19920616,
 19920617,
 19920618,
 19920619,
 19920622,
 19920623,
 19920624,
 19920625,
 19920626,
 19920629,
 19920630,
 19920701,
 19920702,
 19920703,
 19920706,
 19920707,
 19920708,
 19920709,
 19920710,
 19920713,
 19920714,
 19920715,
 19920716,
 19920717,
 19920720,
 19920721,
 19920722,
 19920723,
 19920724,
 19920727,
 19920728,
 19920729,
 19920730,
 19920731,
 19920803,
 19920804,
 19920805,
 19920806,
 19920807,
 19920810,
 19920811,
 19920812,
 19920813,
 19920814,
 19920817,
 19920818,
 19920819,
 19920820,
 19920821,
 19920824,
 19920825,
 19920826,
 19920827,
 19920828,
 19920831,
 19920901,
 19920902,
 19920903,
 19920904,
 19920908,
 19920909,
 19920910,
 19920911,
 19920914,
 19920915,
 19920916,
 19920917,
 19920918,
 19920921,
 19920922,
 19920923,
 19920924,
 19920925,
 19920928,
 19920929,
 19920930,
 19921001,
 19921002,
 19921005,
 19921006,
 19921007,
 19921008,
 19921009,
 19921012,
 19921013,
 19921014,
 19921015,
 19921016,
 19921019,
 19921020,
 19921021,
 19921022,
 19921023,
 19921026,
 19921027,
 19921028,
 19921029,
 19921030,
 19921102,
 19921103,
 19921104,
 19921105,
 19921106,
 19921109,
 19921110,
 19921111,
 19921112,
 19921113,
 19921116,
 19921117,
 19921118,
 19921119,
 19921120,
 19921123,
 19921124,
 19921125,
 19921126,
 19921127,
 19921130,
 19921201,
 19921202,
 19921203,
 19921204,
 19921207,
 19921208,
 19921209,
 19921210,
 19921211,
 19921214,
 19921215,
 19921216,
 19921217,
 19921218,
 19921221,
 19921222,
 19921223,
 19921224,
 19921228,
 19921229,
 19921230,
 19921231,
 19930104,
 19930105,
 19930106,
 19930107,
 19930108,
 19930111,
 19930112,
 19930113,
 19930114,
 19930115,
 19930118,
 19930119,
 19930120,
 19930121,
 19930122,
 19930125,
 19930126,
 19930127,
 19930128,
 19930129,
 19930201,
 19930202,
 19930203,
 19930204,
 19930205,
 19930208,
 19930209,
 19930210,
 19930211,
 19930212,
 19930215,
 19930216,
 19930217,
 19930218,
 19930219,
 19930222,
 19930223,
 19930224,
 19930225,
 19930226,
 19930301,
 19930302,
 19930303,
 19930304,
 19930305,
 19930308,
 19930309,
 19930310,
 19930311,
 19930312,
 19930315,
 19930316,
 19930317,
 19930318,
 19930319,
 19930322,
 19930323,
 19930324,
 19930325,
 19930326,
 19930329,
 19930330,
 19930331,
 19930401,
 19930402,
 19930405,
 19930406,
 19930407,
 19930408,
 19930412,
 19930413,
 19930414,
 19930415,
 19930416,
 19930419,
 19930420,
 19930421,
 19930422,
 19930423,
 19930426,
 19930427,
 19930428,
 19930429,
 19930430,
 19930503,
 19930504,
 19930505,
 19930506,
 19930507,
 19930510,
 19930511,
 19930512,
 19930513,
 19930514,
 19930517,
 19930518,
 19930519,
 19930520,
 19930521,
 19930524,
 19930525,
 19930526,
 19930527,
 19930528,
 19930531,
 19930601,
 19930602,
 19930603,
 19930604,
 19930607,
 19930608,
 19930609,
 19930610,
 19930611,
 19930614,
 19930615,
 19930616,
 19930617,
 19930618,
 19930621,
 19930622,
 19930623,
 19930624,
 19930625,
 19930628,
 19930629,
 19930630,
 19930701,
 19930702,
 19930705,
 19930706,
 19930707,
 19930708,
 19930709,
 19930712,
 19930713,
 19930714,
 19930715,
 19930716,
 19930719,
 19930720,
 19930721,
 19930722,
 19930723,
 19930726,
 19930727,
 19930728,
 19930729,
 19930730,
 19930802,
 19930803,
 19930804,
 19930805,
 19930806,
 19930809,
 19930810,
 19930811,
 19930812,
 19930813,
 19930816,
 19930817,
 19930818,
 19930819,
 19930820,
 19930823,
 19930824,
 19930825,
 19930826,
 19930827,
 19930830,
 19930831,
 19930901,
 19930902,
 19930903,
 19930907,
 19930908,
 19930909,
 19930910,
 19930913,
 19930914,
 19930915,
 19930916,
 19930917,
 19930920,
 19930921,
 19930922,
 19930923,
 19930924,
 19930927,
 19930928,
 19930929,
 19930930,
 19931001,
 19931004,
 19931005,
 19931006,
 19931007,
 19931008,
 19931011,
 19931012,
 19931013,
 19931014,
 19931015,
 19931018,
 19931019,
 19931020,
 19931021,
 19931022,
 19931025,
 19931026,
 19931027,
 19931028,
 19931029,
 19931101,
 19931102,
 19931103,
 19931104,
 19931105,
 19931108,
 19931109,
 19931110,
 19931111,
 19931112,
 19931115,
 19931116,
 19931117,
 19931118,
 19931119,
 ...]

# create the rebalance matrix:

In [137]:
#get weight table from mean variance
#weight = pd.read_excel('weights_table_mean_variance.xlsx')
weight = pd.read_excel('mean_weighted_user8.xlsx')

#get unique stock name from table
stocks_name = list(set(weight['tic']))
stocks_name.sort()

In [208]:
weight.head()

   tic  predicted_return   weights  trade_date
0  EOG          0.033723  0.000186    19950601
1  EQT          0.037745  0.000000    19950601
2  HES          0.051450  0.005125    19950601
3  NFX          0.030283  0.050000    19950601
4  OKE          0.041020  0.000000    19950601

In [142]:
#get unique trade date from table
tradedate = list(set(weight['trade_date']))
tradedate.sort()

In [143]:
len(tradedate)

89

In [209]:
len(stocks_name)

982

In [144]:
#add the last trade date 20170901
tradedate_full = tradedate.copy()
tradedate_full.append(20170901)

In [145]:
len(tradedate_full)

90

In [146]:
#construct an empty matrix
#rows are stocks: 971 unique stocks
#columns are trade dates
#name the index as stock names
balance_weight = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_weight = balance_weight.fillna(0)

In [148]:
balance_weight.head()

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150302,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601
A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AA.3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AABA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAL,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAP,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [149]:
weight.head()

   tic  predicted_return   weights  trade_date
0  EOG          0.033723  0.000186    19950601
1  EQT          0.037745  0.000000    19950601
2  HES          0.051450  0.005125    19950601
3  NFX          0.030283  0.050000    19950601
4  OKE          0.041020  0.000000    19950601

In [150]:
range(weight.shape[0])

range(0, 12932)

In [151]:
#loop through the weights table to file the matrix
for i in range(weight.shape[0]):
    tics = weight.loc[i, 'tic']
    date = weight.loc[i, 'trade_date']
    w = weight.loc[i, 'weights']
    balance_weight.loc[tics, date] = w

In [152]:
balance_weight.head()

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150302,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601
A,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
AA.3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
AABA,0.0,0.0,0.0,0.0,0.0,0.031323,0.0,0.0,0.0,0.008345,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
AAL,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.014821,0.0,0.0,0.0,0.0,0.000000
AAP,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.038554

In [153]:
#save to Excel file
import xlsxwriter
#writer = pd.ExcelWriter('balance_weight.xlsx')
writer = pd.ExcelWriter('balance_weight_user8.xlsx')

balance_weight.to_excel(writer,'Sheet1')
writer.save()

In [154]:
# weighted
# mean-variance shares matrix
balance_share = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_share['initial'] = 0
balance_share = balance_share.fillna(0)
#mean-variance cost matrix
balance_cost = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_cost = balance_cost.fillna(0)
#mean-variance cash matrix
balance_cash = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_cash = balance_cash.fillna(0)

#mean-variance portfolio value
portfolio = pd.DataFrame(index = range(1), columns = tradedate_full)
portfolio.loc[0,tradedate[0]] = capital

In [155]:
portfolio

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601,20170901
0,1000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
# equally weight
weight_tmp = weight.copy()
for i in tradedate:
    ind = np.where(weight_tmp['trade_date'] == i)[0]
    we = 1/len(ind)
    weight_tmp.loc[ind, 'weights'] = we

# create the equally weighted matrix:
equal_weight = pd.DataFrame(index = stocks_name, columns = tradedate)
equal_weight = equal_weight.fillna(0)

for i in range(weight_tmp.shape[0]):
    tics = weight_tmp.loc[i, 'tic']
    date = weight_tmp.loc[i, 'trade_date']
    w = weight_tmp.loc[i, 'weights']
    equal_weight.loc[tics, date] = w
import xlsxwriter
#writer2 = pd.ExcelWriter('equal_weight.xlsx')
writer2 = pd.ExcelWriter('equal_weight_user8.xlsx')

equal_weight.to_excel(writer2,'Sheet1')
writer2.save()

In [159]:
equal_weight.head()

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150302,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601
A,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.007143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
AA.3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
AABA,0.0,0.0,0.0,0.0,0.0,0.005814,0.006061,0.0,0.006849,0.006711,...,0.000000,0.000000,0.007143,0.007463,0.000000,0.000000,0.007576,0.007576,0.007576,0.000000
AAL,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,...,0.007353,0.007299,0.007143,0.007463,0.007463,0.007519,0.007576,0.007576,0.007576,0.007752
AAP,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.007143,0.007463,0.007463,0.000000,0.007576,0.007576,0.007576,0.007752

In [160]:
# the equally weight
balance_share_equal = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_share_equal['initial'] = 0
balance_share_equal = balance_share_equal.fillna(0)
balance_cost_equal = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_cost_equal = balance_cost_equal.fillna(0)
balance_cash_equal = pd.DataFrame(index = stocks_name, columns = tradedate)
balance_cash_equal = balance_cash_equal.fillna(0)

portfolio_equal = pd.DataFrame(index = range(1), columns = tradedate_full)
portfolio_equal.loc[0,tradedate[0]] = capital

In [161]:
start_time = time.time()
portfolio_equal
elapsed_time = time.time() - start_time
print(elapsed_time)
print(len(stocks_name),len(daily))

4.8160552978515625e-05
982 7155

In [ ]:
##################DON'T RUN THIS LINE#######################
# backtest daily price matrix:
# covert original table to matrix
# rows = all stocks: 971, columns = all dates:7155 days
start_time = time.time()

balance_daily = pd.DataFrame(index = stocks_name, columns = daily)
balance_daily = balance_daily.fillna(np.nan)

for i in stocks_name:
    ind = np.where(data_adj['tic'] == i)[0]
    tmp = data_adj.loc[ind, :]
    tmp.index = range(tmp.shape[0])
    for j in daily:
        ind2 = np.where(tmp['datadate'] == j)[0]
        if(len(ind2) != 0):
            balance_daily.loc[i,j] = tmp.loc[ind2[0], 'adj_price']

elapsed_time = time.time() - start_time
print(elapsed_time)
writer2 = pd.ExcelWriter('balance_daily.xlsx')
balance_daily.to_excel(writer2,'Sheet1')
writer2.save()
###############################################

In [103]:
balance_daily = pd.read_excel('excel_output/balance_daily.xlsx')
balance_daily = pd.read_excel('excel_output/balance_daily_user8.xlsx')

In [200]:
#balance_price = balance_daily[tradedate]
#balance_price = balance_price.fillna(0)
balance_price.head()

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150302,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601
A,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,42.700000,40.920000,34.750000,41.060000,38.590000,45.95000,46.990000,43.21,52.04,60.73
AA.3,34.688367,42.657316,43.032326,42.938573,46.313658,47.157429,47.813695,54.188855,55.126378,63.892597,...,44.854485,37.263726,27.662766,28.442844,27.332733,27.90279,30.393039,0.00,0.00,0.00
AABA,0.000000,0.000000,0.000000,0.000000,1.135417,0.791667,0.791667,1.250000,1.380208,2.492188,...,44.110000,43.350000,31.600000,33.710000,32.800000,36.65000,42.930000,39.63,46.24,50.65
AAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,48.310000,44.180000,39.200000,43.260000,41.830000,31.95000,36.240000,45.75,47.09,49.05
AAP,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,154.770000,153.320000,172.620000,162.340000,153.350000,153.34000,158.760000,170.76,156.68,137.10

In [202]:
# mean variance weighted portfolio:
balance_price_full = []
balance_price_full = balance_daily[tradedate_full]
balance_price = balance_daily[tradedate]
for j in range(len(tradedate)):
    i = tradedate[j]
    cap = portfolio.loc[0, i]
    balance_cash[i] = cap * balance_weight[i]
    balance_share[i] = list(np.array(balance_cash[i])
                                  / np.array(balance_price[i]))
    balance_share[i] = balance_share[i].fillna(0)
    balance_share[i] = balance_share[i].astype(int)
    #next quarter price * current share to calculate next quarter total account value
    a = balance_price_full[tradedate_full[j+1]].fillna(0)
    portfolio.loc[0, tradedate_full[j+1]] = np.dot(balance_share[i], a)

    

balance_cost = abs(np.diff(balance_share, axis = 1))
balance_cost = balance_cost * balance_price
balance_cost = np.sum(balance_cost, axis = 0) * transaction_percent
balance_cost['20170901'] = 0

ValueError: operands could not be broadcast together with shapes (982,) (971,)

In [210]:
balance_price

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150302,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601
A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.700000,40.920000,34.750000,41.060000,38.590000,45.95000,46.990000,43.21,52.04,60.73
AA.3,34.688367,42.657316,43.032326,42.938573,46.313658,47.157429,47.813695,54.188855,55.126378,63.892597,...,44.854485,37.263726,27.662766,28.442844,27.332733,27.90279,30.393039,NaN,NaN,NaN
AABA,NaN,NaN,NaN,NaN,1.135417,0.791667,0.791667,1.250000,1.380208,2.492188,...,44.110000,43.350000,31.600000,33.710000,32.800000,36.65000,42.930000,39.63,46.24,50.65
AAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.310000,44.180000,39.200000,43.260000,41.830000,31.95000,36.240000,45.75,47.09,49.05
AAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,154.770000,153.320000,172.620000,162.340000,153.350000,153.34000,158.760000,170.76,156.68,137.10
AAPL,1.506714,1.533500,1.343750,0.959821,0.883929,0.861607,0.897321,0.575893,0.604929,0.799107,...,129.090000,130.535000,107.720000,117.340000,100.530000,98.46000,106.730000,109.49,139.79,153.18
ABBV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.460000,66.930000,60.500000,59.020000,56.340000,62.83000,64.030000,59.16,62.83,66.71
ABC,2.875000,2.828125,3.687500,3.500000,4.187500,4.781250,5.031250,6.265625,5.484375,6.351625,...,103.100000,113.260000,99.270000,99.500000,87.430000,75.64000,87.150000,77.80,92.23,93.14
ABI.3,8.718750,8.468750,9.062500,11.250000,13.468750,13.000000,15.343750,17.593750,19.062500,18.937500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABS.1,28.500000,32.125000,31.375000,37.250000,38.750000,42.250000,35.000000,34.625000,34.125000,34.188000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABT,20.000000,19.250000,19.687500,21.125000,21.312500,22.750000,27.625000,28.500000,31.312500,31.094000,...,47.220000,48.940000,43.570000,45.460000,39.330000,39.50000,42.300000,37.60,45.59,46.10
ABX,25.375000,25.125000,26.125000,30.125000,31.750000,27.500000,29.250000,27.875000,24.750000,22.625000,...,12.760000,11.820000,6.750000,7.600000,13.270000,16.90000,17.800000,15.02,18.91,16.24
ACAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.750000,...,14.650000,14.190000,13.480000,15.550000,13.850000,16.05000,16.920000,17.33,NaN,NaN
ACN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,91.180000,96.190000,92.290000,108.130000,103.450000,119.01000,115.060000,117.66,124.07,125.29
ACS,7.000000,7.562500,8.062500,8.937500,12.281250,13.437500,14.500000,10.375000,13.687500,13.312500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACV.1,10.750000,9.375000,10.625000,11.958333,13.125000,13.666667,15.916667,19.666667,18.666667,19.916667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ADBE,6.554750,6.226625,8.375000,4.078125,4.515625,4.406250,5.421875,4.593750,5.648500,5.078125,...,79.790000,79.870000,75.990000,92.550000,88.370000,100.04000,102.900000,99.51,120.35,141.38
ADCT,26.467757,36.529880,37.732960,34.342462,40.685974,48.670050,66.065803,48.564928,57.971649,64.863493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ADI,7.968949,8.468962,9.093977,9.375234,10.312758,8.953349,12.844071,11.187500,13.375000,17.000000,...,59.775000,68.750000,53.550000,61.570000,54.700000,58.65000,63.060000,69.01,83.76,82.21
ADM,13.147609,12.405791,13.058727,14.457876,14.457876,13.907389,16.747630,14.495025,15.474418,18.151378,...,47.850000,53.030000,43.340000,36.700000,35.480000,42.83000,43.140000,44.31,46.51,41.82
ADNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.03,67.72,69.87
ADP,15.562500,16.500000,19.968750,19.625000,18.687500,20.687500,21.375000,21.625000,24.500000,23.406500,...,90.180000,85.300000,75.100000,87.560000,86.770000,88.12000,90.630000,95.77,104.53,103.35
ADS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,282.290000,297.140000,252.400000,289.160000,213.510000,222.62000,210.190000,228.18,247.62,241.65
ADSK,9.500000,11.312500,8.875000,8.812500,8.562500,5.687500,7.031250,8.281250,9.718750,11.250000,...,64.000000,54.390000,45.490000,64.720000,54.310000,58.30000,67.370000,69.22,88.93,113.03
ADT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.080000,36.680000,31.870000,35.960000,40.730000,NaN,NaN,NaN,NaN,NaN
AEE,37.000000,34.875000,40.500000,42.500000,39.125000,37.250000,39.625000,38.500000,36.500000,37.563000,...,42.190000,40.220000,39.120000,43.830000,46.930000,49.43000,49.150000,48.91,54.76,56.80
AEP,34.250000,34.125000,37.875000,43.000000,39.875000,40.875000,40.625000,41.625000,40.250000,44.250000,...,56.150000,56.010000,52.990000,56.730000,61.730000,64.89000,64.410000,58.16,66.12,72.21
AES,4.218750,4.625000,5.125000,6.062500,6.750000,8.906250,12.062500,16.156250,18.406250,18.750000,...,12.650000,13.640000,11.440000,9.980000,10.120000,10.94000,12.010000,11.03,11.35,11.95
AET,14.906250,17.343750,18.187500,18.812500,18.375000,16.250000,17.968750,21.187500,25.000000,24.453250,...,100.500000,119.620000,111.550000,107.500000,110.540000,115.29000,116.160000,134.90,130.04,147.65
AFL,7.145833,6.791667,6.875000,7.937500,7.437500,8.406250,10.468750,10.218750,12.593750,13.843750,...,62.570000,62.100000,56.650000,65.990000,61.070000,69.41000,73.870000,70.48,72.98,75.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLP.1,21.656791,22.500563,23.250581,25.500638,17.750000,15.312500,15.500000,21.312500,24.062500,28.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WLTW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,127.443709,126.119205,112.529801,121.695364,115.510000,128.07000,124.850000,121.42,131.04,146.63
WM,14.750000,19.500000,21.000000,22.000000,29.625000,29.000000,32.125000,35.500000,37.250000,42.125000,...,54.850000,49.740000,49.310000,53.920000,57.050000,60.98000,64.000000,69.29,73.37,73.46
WMB,11.166667,12.125000,14.208333,15.958333,16.500000,16.958333,18.750000,21.875000,22.000000,24.594000,...,49.030000,51.320000,46.010000,36.660000,16.550000,22.59000,28.150000,30.02,28.79,28.81
WMT,12.375000,12.437500,12.125000,10.812500,13.000000,13.250000,12.750000,13.500000,15.187500,18.844000,...,83.960000,74.730000,63.820000,58.990000,66.460000,70.50000,72.840000,70.67,70.45,79.81
WOR,20.125000,20.125000,20.875000,21.375000,20.000000,20.375000,20.125000,20.625000,18.438000,18.813000,...,27.130000,27.100000,24.290000,31.120000,32.060000,38.21000,43.380000,56.73,51.00,42.99
WPX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.770000,12.720000,7.020000,8.350000,4.230000,10.57000,12.270000,15.00,13.27,11.00
WRK,7.215909,7.840909,7.159091,7.613636,8.977273,8.522727,10.250000,9.562500,7.562500,10.531500,...,68.840000,64.540000,58.430000,51.020000,35.400000,39.59000,48.510000,50.92,54.56,55.27
WWY,17.700000,18.150000,18.900000,23.350000,21.250000,21.600000,23.100000,23.650000,23.450000,29.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WY,43.625000,46.125000,45.125000,42.000000,45.625000,44.750000,47.125000,46.500000,49.625000,58.063000,...,35.200000,32.500000,27.590000,32.140000,26.650000,31.32000,31.870000,30.61,34.07,33.51
WYE,18.468750,19.250000,22.937500,25.000000,27.250000,29.500000,32.187500,32.437500,37.625000,37.594000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94.110000,84.870000,75.130000,76.630000,74.670000,67.55000,70.740000,73.84,84.17,102.84
WYNN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,142.430000,98.290000,70.990000,66.810000,84.510000,96.73000,93.170000,99.27,102.71,133.59
X,33.500000,32.875000,33.125000,32.875000,30.125000,29.500000,30.625000,31.000000,32.875000,36.375000,...,23.820000,23.890000,15.890000,8.090000,9.190000,14.07000,19.330000,32.03,39.68,20.50
XEC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,109.850000,115.110000,105.610000,122.290000,85.960000,115.89000,134.620000,137.51,128.45,107.25
XEL,23.312500,21.375000,23.500000,25.062500,23.375000,22.375000,23.500000,23.937500,24.250000,24.250000,...,34.410000,34.070000,32.980000,35.970000,39.460000,41.56000,41.270000,38.54,43.50,48.13
XL,23.312500,28.187500,31.062500,35.000000,34.875000,33.500000,37.750000,44.500000,44.500000,55.063000,...,36.540000,37.620000,36.300000,38.760000,35.560000,34.23000,34.330000,35.87,41.12,43.62
XLNX,7.156250,10.843750,7.718750,7.812500,8.500000,9.156250,11.125000,11.250000,13.218750,12.093750,...,42.110000,48.330000,40.310000,50.240000,48.210000,47.37000,54.240000,53.39,59.68,66.65
XOM,17.812500,17.437500,19.437500,19.937500,21.000000,20.937500,23.718750,24.812500,30.000000,32.000000,...,88.040000,85.130000,72.080000,81.890000,81.280000,89.24000,86.840000,87.24,83.02,80.70
XRAY,6.000000,6.177167,6.145833,6.479167,7.083333,6.666667,7.781333,8.750000,8.270833,9.395833,...,53.420000,52.310000,50.740000,61.970000,60.430000,62.48000,61.650000,57.46,64.50,64.06
XRX,76.416667,81.333333,91.916667,86.416667,105.916667,111.250000,99.250000,125.750000,137.000000,154.500000,...,54.320000,45.840000,39.120000,42.760000,39.720000,39.92000,39.480000,37.80,29.56,28.40
XTO,1.137778,1.031111,1.226667,1.173333,1.591111,1.733333,1.751111,1.893333,2.120000,2.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
XYL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.170000,36.600000,31.130000,37.640000,37.940000,44.82000,50.410000,51.81,49.55,52.44
YNR.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YRCW,187500.000000,140000.000000,123750.000000,111250.000000,127500.000000,133750.000000,148750.000000,157500.000000,195000.000000,312500.000000,...,19.380000,13.200000,15.280000,17.100000,8.640000,9.20000,11.580000,13.15,13.19,9.51
YUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.800000,90.270000,79.100000,74.480000,76.190000,82.43000,90.760000,62.69,65.57,73.83
ZBH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,121.390000,114.770000,100.650000,102.720000,97.390000,122.15000,128.350000,99.79,118.89,122.67
ZE,7.750000,8.500000,7.500000,6.750000,14.000000,14.625000,13.125000,9.375000,11.125000,10.438000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZION,11.062500,14.000000,17.562500,18.562500,18.937500,21.687500,25.375000,30.625000,30.750000,38.125000,...,27.110000,28.600000,27.660000,30.410000,22.310000,28.39000,30.570000,40.41,46.53,40.55
ZRN,20.250000,21.875000,24.500000,21.125000,20.375000,21.000000,28.625000,25.250000,26.625000,29.625000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [197]:
np.array(balance_price[i])

array([             nan,   3.46883672e+01,              nan,
                    nan,              nan,   1.50671429e+00,
                    nan,   2.87500000e+00,   8.71875000e+00,
         2.85000000e+01,   2.00000000e+01,   2.53750000e+01,
                    nan,              nan,   7.00000000e+00,
         1.07500000e+01,   6.55475000e+00,   2.64677575e+01,
         7.96894922e+00,   1.31476086e+01,              nan,
         1.55625000e+01,              nan,   9.50000000e+00,
                    nan,   3.70000000e+01,   3.42500000e+01,
         4.21875000e+00,   1.49062500e+01,   7.14583333e+00,
                    nan,   1.73125000e+01,   1.85000000e+01,
         6.71875000e+00,   2.27500000e+01,   3.59118205e+02,
         1.83750000e+01,              nan,   8.65625000e+00,
                    nan,   1.40625000e+01,   2.95000000e+01,
         7.81250000e+00,              nan,   4.12500000e+00,
         1.48750000e+01,              nan,              nan,
         2.81880000e+01,   4.96093750e+00,              nan,
         1.69375000e+01,   2.64814815e+00,              nan,
         9.07812500e+00,   1.27500000e+01,              nan,
                    nan,   2.42500000e+01,              nan,
         6.81250000e+00,   3.40625000e+01,   5.68750000e+00,
         2.14444444e+01,              nan,              nan,
                    nan,              nan,   3.36250000e+01,
         1.61666667e+01,   2.58333333e+00,   1.25541126e+01,
         1.08750000e+01,   8.87500000e+00,   2.63750000e+01,
         1.73437500e+00,   2.39232349e+00,   2.92500000e+01,
         5.79375000e+01,              nan,   1.28750000e+01,
         6.37500000e+00,   1.34375000e+01,   3.66250000e+01,
         1.02460000e+01,   9.85185185e+00,   2.42500000e+01,
         4.87500000e+00,   2.50649351e+01,   2.70000000e+01,
                    nan,   1.81250000e+01,   1.82500000e+01,
         8.43750000e+00,   2.03750000e+01,   7.00000000e+00,
                    nan,              nan,   1.20416667e+01,
         2.46250000e+01,              nan,   1.04375000e+01,
         2.36250000e+01,   2.93125000e+01,   1.41875000e+01,
         1.73750000e+01,   2.52500000e+01,   2.76562500e+00,
         1.11250000e+01,   2.69444444e+00,   1.86250000e+01,
         2.42500000e+01,   1.45625000e+01,   3.30000000e+01,
         1.45937500e+01,   4.05000000e+01,   4.84722222e+00,
         1.12500000e+01,   4.36666667e+00,   1.03125000e+01,
         1.75625000e+01,   2.27500000e+01,   1.19200000e+01,
         7.29166667e-01,              nan,   3.17187500e+00,
         1.06993322e+01,   1.86250000e+01,              nan,
         2.03125000e+00,   1.51875000e+01,   1.02500000e+01,
         8.07812500e+00,   1.39375000e+01,   1.66250000e+01,
         4.41250000e+01,   6.12500000e+02,   3.23750000e+01,
         2.06250000e+01,              nan,              nan,
         2.30451158e+00,   1.16250000e+01,   1.64541341e+01,
         2.75000000e+01,   7.06250000e+00,   6.30000000e+01,
                    nan,   1.46875000e+01,              nan,
         3.25000000e+00,   5.37500000e+00,              nan,
         7.25000000e+01,   2.23125000e+01,   4.12500000e+01,
         1.96296296e+01,   1.63125000e+01,   1.33333333e+01,
         9.66666667e+00,              nan,   1.64444444e+02,
         1.51250000e+01,   8.37500000e+00,   2.04687500e+01,
         1.85000000e+01,              nan,   2.84028583e+00,
                    nan,   4.52500000e+01,   1.48750000e+01,
         7.08333333e+00,              nan,   4.68750000e+01,
         1.15000000e+01,   1.36250000e+01,   6.58333333e+00,
         2.09876543e+00,   2.57500000e+01,   3.85416667e-01,
         2.37500000e+01,   1.03750000e+01,   3.71875000e+00,
                    nan,   9.48333452e+00,   4.68750000e+00,
         3.31250000e+01,              nan,   4.70000000e+01,
         1.73958333e+00,   1.33282500e+01,   5.80555556e+00,
         4.12500000e+00,              nan,              nan,
                    nan,   1.57649227e+01,              nan,
         9.59375000e+00,   4.84375000e+00,   1.47187500e+01,
         2.10000000e+01,   5.62500000e+00,              nan,
                    nan,   1.13437500e+01,   2.43750000e+01,
         4.95833333e+00,   1.88750000e+01,   2.84166667e+01,
                    nan,              nan,              nan,
         2.13750000e+01,   2.40000000e+01,              nan,
                    nan,   7.16666667e+00,   1.31250000e+00,
                    nan,   3.29690000e+01,   3.00030003e+00,
         1.80000000e+01,   7.00000000e+00,              nan,
                    nan,   2.41875000e+01,              nan,
         8.00000000e+00,   3.76562500e+00,   1.51111111e+01,
         5.37500000e+01,   2.49655556e+00,   2.53750000e+01,
         2.57500000e+01,              nan,   6.26041667e+00,
         1.15833333e+01,   2.48750000e+01,   1.27777778e+01,
                    nan,   7.34375000e+00,              nan,
                    nan,   2.20000000e+01,   9.38888889e+00,
         9.50000000e+00,   2.47500000e+01,              nan,
         2.68750000e+01,   2.35000000e+01,              nan,
         1.86875000e+01,   3.97500000e+01,              nan,
                    nan,   3.37500000e+01,   1.40625000e+01,
         2.83750000e+01,   1.43125000e+01,   4.57500000e+01,
                    nan,              nan,   7.87500000e+00,
                    nan,   2.23210218e+00,   3.82812500e+00,
         1.86250000e+01,              nan,              nan,
         3.65000000e+01,              nan,   1.44855967e+00,
         3.18750000e+01,              nan,   1.06000000e+02,
                    nan,              nan,   1.64375000e+01,
                    nan,   1.39375000e+01,   7.25000000e+00,
         3.01250000e+01,   1.67031098e+01,   6.26312631e+01,
                    nan,   1.08750000e+01,   2.35000000e+01,
         2.43750000e+01,   2.65000000e+01,              nan,
         6.78125000e+00,              nan,   2.80000000e+01,
         6.31250000e+00,   9.00000000e+00,   2.98750000e+01,
         4.28750000e+01,   2.97500000e+01,   1.57500000e+01,
         1.72500000e+01,              nan,   2.93750000e+00,
         2.00000000e+00,   2.99375000e+01,   1.70000000e+01,
                    nan,   1.82500000e+01,   6.03125000e+00,
                    nan,   1.40000000e+01,              nan,
                    nan,   1.45625000e+01,   7.50000000e+00,
         2.36250000e+01,   1.03906250e+00,   1.77500000e+01,
         8.31250000e+00,              nan,   1.52500000e+01,
         2.47500000e+01,   2.17000000e+02,              nan,
                    nan,   1.40625000e+01,   1.42187500e+00,
                    nan,              nan,   1.71624714e+01,
         3.43750000e+00,              nan,   1.77500000e+01,
                    nan,   4.19874038e+01,              nan,
                    nan,   4.25000000e+00,   1.48125000e+01,
         2.15000000e+01,              nan,   1.67500000e+01,
         9.37207123e+00,              nan,              nan,
         3.98148148e+00,   1.06666667e+01,   2.70000000e+01,
         6.75000000e+00,   1.52500000e+01,   1.65625000e+00,
         2.61250000e+01,   2.55000000e+01,   6.87500000e+00,
         2.08750000e+01,   1.60312500e+01,   1.73125000e+01,
         1.37500000e+01,   2.31875000e+01,   3.55555556e+00,
         9.75000000e+00,   2.28750000e+01,   2.13750000e+01,
         5.53125000e+00,   6.50000000e+00,              nan,
                    nan,              nan,              nan,
         3.30000000e+02,   2.10000000e+01,   2.47500000e+01,
         2.61250000e+01,   3.50000000e+00,   1.09687500e+01,
         5.87500000e+00,   8.18750000e+00,   9.66666667e+00,
         9.21875000e+00,   6.75000000e+00,   2.61250000e+02,
         3.20000000e+01,   5.11718750e-01,   1.29062500e+01,
                    nan,   1.07083333e+01,              nan,
         2.59259259e-01,              nan,              nan,
                    nan,   7.87500000e+00,   3.88125000e+01,
         2.60833333e+01,              nan,   4.98148148e+00,
         3.01250000e+01,   2.46875000e+01,   6.51250000e+01,
                    nan,   1.35000000e+02,              nan,
         4.28750000e+01,   3.33750000e+01,   4.46875000e+00,
         2.18750000e+01,   9.75000000e+00,   2.96875000e+01,
         4.18750000e+01,   9.75000000e+00,   8.69047619e+00,
         1.51666667e+01,   1.16055588e+01,              nan,
                    nan,              nan,   2.20000000e+01,
         1.59375000e+01,   1.94166667e+01,   9.19444444e+00,
         1.15000000e+01,   1.67916667e+01,              nan,
         4.40625000e+01,              nan,   5.43209877e+00,
         6.03125000e+00,   1.40625000e+00,   2.01875000e+01,
         3.95000000e+01,   1.50602410e+01,   7.50000000e+00,
         5.28750000e+01,              nan,   1.69687500e+01,
         9.03125000e+00,   3.09375000e+00,   1.32187500e+01,
         6.87500000e+01,              nan,              nan,
         1.06250000e+01,   1.28437500e+01,   5.25000000e+00,
         2.13750000e+01,   1.40000000e+01,   2.35625000e+01,
                    nan,   5.48437500e+00,   4.83750000e+01,
         4.12500000e+00,              nan,   2.50000000e+00,
         3.58125000e+01,              nan,   1.02083333e+00,
                    nan,   2.53750000e+01,   3.75000000e+00,
                    nan,   1.31880000e+01,   7.17187500e+00,
         5.31250000e+00,   3.95000000e+01,   1.20416667e+01,
         1.24583333e+01,              nan,              nan,
         1.19375000e+01,   1.10250000e+02,   1.24375000e+01,
         6.73120000e+00,   5.62500000e+00,   4.39075000e+00,
         7.81250000e-01,   4.83202443e+00,   4.71250000e+01,
         5.40625000e+00,   2.30000000e+01,              nan,
         1.66250000e+01,              nan,              nan,
         7.25000000e+00,   2.01250000e+01,              nan,
         1.59259259e+01,   1.56250000e+01,   7.12500000e+01,
         1.01875000e+01,   3.38125000e+01,   8.87500000e+00,
         7.31250000e+00,   1.53750000e+01,              nan,
                    nan,   8.58333333e+00,   1.77500000e+01,
         2.96875000e+01,   2.75625000e+01,              nan,
                    nan,   1.52500000e+01,              nan,
         3.39062500e+00,   4.39503279e+00,              nan,
         2.72500000e+01,   5.60937500e+00,   2.49166667e+01,
         2.08125000e+01,   9.97916667e+00,   1.10000000e+01,
         1.05000000e+01,   1.76875000e+01,              nan,
         1.05312500e+01,   5.00000000e+00,   9.75000000e+00,
         3.21875000e+01,              nan,              nan,
                    nan,   7.65625000e+00,   1.86562500e+01,
         6.72043011e+00,   3.00625000e+01,   2.21250000e+01,
         1.44375000e+01,              nan,   3.40625000e+00,
         2.17500000e+01,   1.93333333e+01,   1.74375000e+01,
                    nan,   1.98750000e+01,   8.04166667e+00,
         4.34567901e+00,              nan,              nan,
                    nan,              nan,   1.16875000e+01,
                    nan,   2.48750000e+01,   1.95000000e+01,
                    nan,   1.43125000e+01,   1.95000000e+01,
         2.62500000e+01,   2.13750000e+01,   1.87500000e+01,
         5.92592593e+00,   2.00000000e+01,   2.25000000e+01,
                    nan,   3.61250000e+01,              nan,
         1.29375000e+01,   8.70833333e+00,   9.40625000e+00,
         2.71250000e+01,   1.95000000e+01,   1.50000000e+00,
                    nan,   1.08750000e+01,   5.65625000e+00,
                    nan,   5.58024691e+00,   1.96000000e+02,
         7.18750000e+00,   1.03333333e+01,              nan,
         1.08125000e+01,   3.15000000e+01,   3.24375000e+01,
         1.51875000e+01,              nan,   1.04375000e+01,
         3.53750000e+01,   2.10000000e+01,   1.31250000e+01,
         2.94375000e+01,              nan,   2.99583333e-02,
         2.42916667e+01,   1.53600393e+01,              nan,
                    nan,              nan,   2.36250000e+01,
         1.00000000e+01,   1.17424242e+01,   5.25781250e+00,
         1.42615492e+02,   4.58750000e+01,   1.69000000e+01,
                    nan,   2.38125000e+01,   2.70833333e+01,
         1.94444444e+00,   2.31875000e+01,   1.10312500e+01,
         2.17500000e+01,   2.94673540e+01,              nan,
         5.65625000e+00,   1.68750000e+01,   8.44444444e+00,
         2.67500000e+02,   1.57500000e+01,   4.47619048e+00,
         6.90625000e+00,   4.37500000e+00,   5.93750000e+01,
         1.49375000e+01,   3.25000000e+01,              nan,
         3.81250000e+00,   3.87500000e+00,   1.92500000e+01,
         4.27500000e+01,   5.81250000e+01,   3.91666667e+00,
                    nan,   6.93750000e+00,   2.81250000e+01,
         1.72500000e+01,   2.04166667e+01,   2.46093750e+00,
         1.60000000e+01,   3.81250000e+01,              nan,
         1.47500000e+01,   2.61875000e+01,              nan,
         1.94380000e+01,              nan,   4.76562500e+01,
         2.24166667e+01,   1.15000000e+02,   1.27500000e+01,
                    nan,   9.75000000e+00,   1.21875000e+01,
                    nan,   1.03750000e+01,   2.42500000e+01,
                    nan,   6.68750000e+00,   4.18750000e+01,
         1.13750000e+01,   1.00000000e+01,   3.47500000e+01,
                    nan,   1.61666667e+01,   1.33750000e+01,
         1.24057906e+01,   4.75000000e+00,   7.28125000e+00,
         3.38750000e+01,   2.83057851e+01,   2.63888889e+00,
         3.37500000e+00,   1.46250000e+01,   1.15625000e+01,
                    nan,   1.81250000e+01,   4.18104243e+00,
         2.15167549e+00,              nan,   1.88125000e+01,
         2.80000000e+01,   4.81481481e+00,   2.85000000e+01,
         4.30000000e+01,              nan,   7.18750000e+00,
                    nan,              nan,   2.80625000e+01,
         3.79166667e+00,   2.53750000e+01,   9.87500000e+00,
         1.46875000e+01,   2.40625000e+01,   1.28125000e+01,
         7.43750000e+00,              nan,   1.77500000e+01,
         2.63750000e+01,   3.16250000e+01,   3.16666667e+00,
         1.69259259e+01,   1.69750000e+01,   1.31666667e+01,
         3.54687500e+00,              nan,   8.93750000e+00,
         3.61223118e+01,   2.15000000e+01,              nan,
         3.64062500e+00,   4.96250000e+01,   2.70000000e+01,
         1.13750000e+01,   2.51724138e+01,   2.32500000e+01,
         2.03750000e+01,   2.07500000e+01,   9.68750000e+00,
         1.12500000e+01,              nan,   1.57500000e+01,
         6.43750000e+00,              nan,   2.75781250e+01,
                    nan,   1.50000000e+01,              nan,
         3.61250000e+01,              nan,              nan,
         1.29166667e+01,              nan,   1.21875000e+01,
         2.00000000e+01,   4.87500000e+01,              nan,
         4.05000000e+01,   1.58206250e+00,              nan,
                    nan,   2.96875000e-01,              nan,
         2.53750000e+01,   1.18750000e+01,              nan,
         1.63333333e+01,   2.87500000e+00,   3.38750000e+01,
         1.22500000e+01,   7.50000000e+00,              nan,
         1.76250000e+01,   6.12500000e+00,   1.45796209e+01,
         3.60416667e+00,              nan,   2.07261292e+01,
         3.65432099e+00,              nan,              nan,
         4.88750000e+01,              nan,   2.86250000e+01,
         1.94583333e+01,   4.48750000e+01,   8.06250000e+00,
         3.47656250e-01,   5.41666667e+00,   1.08385839e+02,
                    nan,   1.16250000e+01,   3.85625000e+01,
         4.66666667e+00,   1.80000000e+01,              nan,
                    nan,   5.57500000e+01,   2.91875000e+01,
         1.15277778e+01,   1.34973005e+01,              nan,
                    nan,   4.72424873e+00,   9.25781250e-01,
         2.26250000e+01,   2.75925926e+00,   1.40625000e+01,
                    nan,   1.10000000e+01,   1.84375000e+01,
         9.56250000e+00,   1.01250000e+01,   9.90625000e+00,
                    nan,   1.83750000e+01,   1.15625000e+01,
         4.16666667e+00,   4.59375000e+00,   2.39392657e+01,
         1.70000000e+01,   1.82500000e+01,   1.62187500e+01,
                    nan,   3.87500000e+00,   3.90000000e+01,
         2.34166667e+01,              nan,              nan,
         1.41250000e+01,   3.27500000e+01,   4.53744037e+01,
         2.20000000e+01,   7.25000000e+00,   2.52500000e+01,
         2.48750000e+01,   9.29687500e+00,   3.82720114e+00,
         1.32500000e+01,   2.64261144e+01,              nan,
         1.67907966e+01,   1.07500000e+01,   4.79976001e+01,
         2.85625000e+01,   7.47916667e+00,   7.43750000e+00,
         8.43750000e+00,              nan,   5.37500000e+00,
         1.96666667e+01,   1.56875000e+01,              nan,
         1.00630032e+02,   2.00625000e+01,   4.54166667e+00,
         1.89062500e+00,   9.15625000e+00,   1.54375000e+02,
         4.84375000e+00,   2.86725000e+00,   6.78125000e+00,
         2.24375000e+01,   1.69166667e+02,   2.95000000e+01,
         8.50000000e+00,              nan,              nan,
         1.38750000e+01,   2.18750000e+01,   1.52500000e+01,
                    nan,   2.40000000e+02,   1.34375000e+01,
         3.00000000e+00,   2.67500000e+01,   6.03125000e+00,
         4.40000000e+01,   1.21250000e+01,              nan,
         4.04687500e+00,   2.17500000e+01,   8.20312500e-01,
         2.10625000e+01,   8.18750000e+00,   2.32500000e+01,
         8.80555556e+00,   2.42500000e+01,   3.33750000e+01,
         1.17916667e+01,              nan,              nan,
         4.50000000e+00,              nan,   3.88125000e+01,
         1.19925000e+00,              nan,   1.45000000e+01,
         4.75000000e+00,   9.12500000e+00,              nan,
                    nan,   3.23439521e+00,   1.98125000e+01,
         7.56250000e+00,   1.50000000e+01,   1.75000000e+01,
         2.70625000e+01,              nan,              nan,
         2.73750000e+01,   1.42500000e+01,   2.21250000e+01,
         3.45312500e+00,   1.06250000e+02,              nan,
         1.18649842e+01,   4.73437500e+00,   2.20625000e+01,
         1.35937500e+01,   1.80000000e+01,              nan,
                    nan,   1.12893750e+00,              nan,
         4.86111111e+00,   1.44166667e+01,   2.43750000e+01,
         2.65000000e+01,   3.10000000e+01,   2.05000000e+01,
         2.96250000e+01,   9.68750000e+00,              nan,
         1.31562500e+01,              nan,   6.59375000e+00,
                    nan,   5.18750000e+00,   5.31250000e+00,
         1.84166667e+01,   1.70000000e+01,   2.97500000e+01,
                    nan,              nan,   1.27572016e+00,
         7.87500000e+00,              nan,   2.25000000e+01,
         2.77500000e+01,   4.48750000e+01,   1.01666667e+01,
         1.30000000e+01,              nan,   3.75000000e+01,
         2.43125000e+01,   5.90625000e+00,   9.12500000e+00,
         1.43125000e+01,   1.72500000e+01,   7.12500000e+00,
         1.79687500e+00,   2.26562500e+00,   5.73750000e+01,
                    nan,              nan,   1.38125000e+01,
         4.75000000e+00,   2.49375000e+01,   2.16567914e+01,
                    nan,   1.47500000e+01,   1.11666667e+01,
         1.23750000e+01,   2.01250000e+01,              nan,
         7.21590909e+00,   1.77000000e+01,   4.36250000e+01,
         1.84687500e+01,              nan,              nan,
         3.35000000e+01,              nan,   2.33125000e+01,
         2.33125000e+01,   7.15625000e+00,   1.78125000e+01,
         6.00000000e+00,   7.64166667e+01,   1.13777778e+00,
                    nan,              nan,   1.87500000e+05,
                    nan,              nan,   7.75000000e+00,
         1.10625000e+01,   2.02500000e+01])

In [172]:
np.array(balance_price[i])

array([             nan,   3.46883672e+01,              nan,
                    nan,              nan,   1.50671429e+00,
                    nan,   2.87500000e+00,   8.71875000e+00,
         2.85000000e+01,   2.00000000e+01,   2.53750000e+01,
                    nan,              nan,   7.00000000e+00,
         1.07500000e+01,   6.55475000e+00,   2.64677575e+01,
         7.96894922e+00,   1.31476086e+01,              nan,
         1.55625000e+01,              nan,   9.50000000e+00,
                    nan,   3.70000000e+01,   3.42500000e+01,
         4.21875000e+00,   1.49062500e+01,   7.14583333e+00,
                    nan,   1.73125000e+01,   1.85000000e+01,
         6.71875000e+00,   2.27500000e+01,   3.59118205e+02,
         1.83750000e+01,              nan,   8.65625000e+00,
                    nan,   1.40625000e+01,   2.95000000e+01,
         7.81250000e+00,              nan,   4.12500000e+00,
         1.48750000e+01,              nan,              nan,
         2.81880000e+01,   4.96093750e+00,              nan,
         1.69375000e+01,   2.64814815e+00,              nan,
         9.07812500e+00,   1.27500000e+01,              nan,
                    nan,   2.42500000e+01,              nan,
         6.81250000e+00,   3.40625000e+01,   5.68750000e+00,
         2.14444444e+01,              nan,              nan,
                    nan,              nan,   3.36250000e+01,
         1.61666667e+01,   2.58333333e+00,   1.25541126e+01,
         1.08750000e+01,   8.87500000e+00,   2.63750000e+01,
         1.73437500e+00,   2.39232349e+00,   2.92500000e+01,
         5.79375000e+01,              nan,   1.28750000e+01,
         6.37500000e+00,   1.34375000e+01,   3.66250000e+01,
         1.02460000e+01,   9.85185185e+00,   2.42500000e+01,
         4.87500000e+00,   2.50649351e+01,   2.70000000e+01,
                    nan,   1.81250000e+01,   1.82500000e+01,
         8.43750000e+00,   2.03750000e+01,   7.00000000e+00,
                    nan,              nan,   1.20416667e+01,
         2.46250000e+01,              nan,   1.04375000e+01,
         2.36250000e+01,   2.93125000e+01,   1.41875000e+01,
         1.73750000e+01,   2.52500000e+01,   2.76562500e+00,
         1.11250000e+01,   2.69444444e+00,   1.86250000e+01,
         2.42500000e+01,   1.45625000e+01,   3.30000000e+01,
         1.45937500e+01,   4.05000000e+01,   4.84722222e+00,
         1.12500000e+01,   4.36666667e+00,   1.03125000e+01,
         1.75625000e+01,   2.27500000e+01,   1.19200000e+01,
         7.29166667e-01,              nan,   3.17187500e+00,
         1.06993322e+01,   1.86250000e+01,              nan,
         2.03125000e+00,   1.51875000e+01,   1.02500000e+01,
         8.07812500e+00,   1.39375000e+01,   1.66250000e+01,
         4.41250000e+01,   6.12500000e+02,   3.23750000e+01,
         2.06250000e+01,              nan,              nan,
         2.30451158e+00,   1.16250000e+01,   1.64541341e+01,
         2.75000000e+01,   7.06250000e+00,   6.30000000e+01,
                    nan,   1.46875000e+01,              nan,
         3.25000000e+00,   5.37500000e+00,              nan,
         7.25000000e+01,   2.23125000e+01,   4.12500000e+01,
         1.96296296e+01,   1.63125000e+01,   1.33333333e+01,
         9.66666667e+00,              nan,   1.64444444e+02,
         1.51250000e+01,   8.37500000e+00,   2.04687500e+01,
         1.85000000e+01,              nan,   2.84028583e+00,
                    nan,   4.52500000e+01,   1.48750000e+01,
         7.08333333e+00,              nan,   4.68750000e+01,
         1.15000000e+01,   1.36250000e+01,   6.58333333e+00,
         2.09876543e+00,   2.57500000e+01,   3.85416667e-01,
         2.37500000e+01,   1.03750000e+01,   3.71875000e+00,
                    nan,   9.48333452e+00,   4.68750000e+00,
         3.31250000e+01,              nan,   4.70000000e+01,
         1.73958333e+00,   1.33282500e+01,   5.80555556e+00,
         4.12500000e+00,              nan,              nan,
                    nan,   1.57649227e+01,              nan,
         9.59375000e+00,   4.84375000e+00,   1.47187500e+01,
         2.10000000e+01,   5.62500000e+00,              nan,
                    nan,   1.13437500e+01,   2.43750000e+01,
         4.95833333e+00,   1.88750000e+01,   2.84166667e+01,
                    nan,              nan,              nan,
         2.13750000e+01,   2.40000000e+01,              nan,
                    nan,   7.16666667e+00,   1.31250000e+00,
                    nan,   3.29690000e+01,   3.00030003e+00,
         1.80000000e+01,   7.00000000e+00,              nan,
                    nan,   2.41875000e+01,              nan,
         8.00000000e+00,   3.76562500e+00,   1.51111111e+01,
         5.37500000e+01,   2.49655556e+00,   2.53750000e+01,
         2.57500000e+01,              nan,   6.26041667e+00,
         1.15833333e+01,   2.48750000e+01,   1.27777778e+01,
                    nan,   7.34375000e+00,              nan,
                    nan,   2.20000000e+01,   9.38888889e+00,
         9.50000000e+00,   2.47500000e+01,              nan,
         2.68750000e+01,   2.35000000e+01,              nan,
         1.86875000e+01,   3.97500000e+01,              nan,
                    nan,   3.37500000e+01,   1.40625000e+01,
         2.83750000e+01,   1.43125000e+01,   4.57500000e+01,
                    nan,              nan,   7.87500000e+00,
                    nan,   2.23210218e+00,   3.82812500e+00,
         1.86250000e+01,              nan,              nan,
         3.65000000e+01,              nan,   1.44855967e+00,
         3.18750000e+01,              nan,   1.06000000e+02,
                    nan,              nan,   1.64375000e+01,
                    nan,   1.39375000e+01,   7.25000000e+00,
         3.01250000e+01,   1.67031098e+01,   6.26312631e+01,
                    nan,   1.08750000e+01,   2.35000000e+01,
         2.43750000e+01,   2.65000000e+01,              nan,
         6.78125000e+00,              nan,   2.80000000e+01,
         6.31250000e+00,   9.00000000e+00,   2.98750000e+01,
         4.28750000e+01,   2.97500000e+01,   1.57500000e+01,
         1.72500000e+01,              nan,   2.93750000e+00,
         2.00000000e+00,   2.99375000e+01,   1.70000000e+01,
                    nan,   1.82500000e+01,   6.03125000e+00,
                    nan,   1.40000000e+01,              nan,
                    nan,   1.45625000e+01,   7.50000000e+00,
         2.36250000e+01,   1.03906250e+00,   1.77500000e+01,
         8.31250000e+00,              nan,   1.52500000e+01,
         2.47500000e+01,   2.17000000e+02,              nan,
                    nan,   1.40625000e+01,   1.42187500e+00,
                    nan,              nan,   1.71624714e+01,
         3.43750000e+00,              nan,   1.77500000e+01,
                    nan,   4.19874038e+01,              nan,
                    nan,   4.25000000e+00,   1.48125000e+01,
         2.15000000e+01,              nan,   1.67500000e+01,
         9.37207123e+00,              nan,              nan,
         3.98148148e+00,   1.06666667e+01,   2.70000000e+01,
         6.75000000e+00,   1.52500000e+01,   1.65625000e+00,
         2.61250000e+01,   2.55000000e+01,   6.87500000e+00,
         2.08750000e+01,   1.60312500e+01,   1.73125000e+01,
         1.37500000e+01,   2.31875000e+01,   3.55555556e+00,
         9.75000000e+00,   2.28750000e+01,   2.13750000e+01,
         5.53125000e+00,   6.50000000e+00,              nan,
                    nan,              nan,              nan,
         3.30000000e+02,   2.10000000e+01,   2.47500000e+01,
         2.61250000e+01,   3.50000000e+00,   1.09687500e+01,
         5.87500000e+00,   8.18750000e+00,   9.66666667e+00,
         9.21875000e+00,   6.75000000e+00,   2.61250000e+02,
         3.20000000e+01,   5.11718750e-01,   1.29062500e+01,
                    nan,   1.07083333e+01,              nan,
         2.59259259e-01,              nan,              nan,
                    nan,   7.87500000e+00,   3.88125000e+01,
         2.60833333e+01,              nan,   4.98148148e+00,
         3.01250000e+01,   2.46875000e+01,   6.51250000e+01,
                    nan,   1.35000000e+02,              nan,
         4.28750000e+01,   3.33750000e+01,   4.46875000e+00,
         2.18750000e+01,   9.75000000e+00,   2.96875000e+01,
         4.18750000e+01,   9.75000000e+00,   8.69047619e+00,
         1.51666667e+01,   1.16055588e+01,              nan,
                    nan,              nan,   2.20000000e+01,
         1.59375000e+01,   1.94166667e+01,   9.19444444e+00,
         1.15000000e+01,   1.67916667e+01,              nan,
         4.40625000e+01,              nan,   5.43209877e+00,
         6.03125000e+00,   1.40625000e+00,   2.01875000e+01,
         3.95000000e+01,   1.50602410e+01,   7.50000000e+00,
         5.28750000e+01,              nan,   1.69687500e+01,
         9.03125000e+00,   3.09375000e+00,   1.32187500e+01,
         6.87500000e+01,              nan,              nan,
         1.06250000e+01,   1.28437500e+01,   5.25000000e+00,
         2.13750000e+01,   1.40000000e+01,   2.35625000e+01,
                    nan,   5.48437500e+00,   4.83750000e+01,
         4.12500000e+00,              nan,   2.50000000e+00,
         3.58125000e+01,              nan,   1.02083333e+00,
                    nan,   2.53750000e+01,   3.75000000e+00,
                    nan,   1.31880000e+01,   7.17187500e+00,
         5.31250000e+00,   3.95000000e+01,   1.20416667e+01,
         1.24583333e+01,              nan,              nan,
         1.19375000e+01,   1.10250000e+02,   1.24375000e+01,
         6.73120000e+00,   5.62500000e+00,   4.39075000e+00,
         7.81250000e-01,   4.83202443e+00,   4.71250000e+01,
         5.40625000e+00,   2.30000000e+01,              nan,
         1.66250000e+01,              nan,              nan,
         7.25000000e+00,   2.01250000e+01,              nan,
         1.59259259e+01,   1.56250000e+01,   7.12500000e+01,
         1.01875000e+01,   3.38125000e+01,   8.87500000e+00,
         7.31250000e+00,   1.53750000e+01,              nan,
                    nan,   8.58333333e+00,   1.77500000e+01,
         2.96875000e+01,   2.75625000e+01,              nan,
                    nan,   1.52500000e+01,              nan,
         3.39062500e+00,   4.39503279e+00,              nan,
         2.72500000e+01,   5.60937500e+00,   2.49166667e+01,
         2.08125000e+01,   9.97916667e+00,   1.10000000e+01,
         1.05000000e+01,   1.76875000e+01,              nan,
         1.05312500e+01,   5.00000000e+00,   9.75000000e+00,
         3.21875000e+01,              nan,              nan,
                    nan,   7.65625000e+00,   1.86562500e+01,
         6.72043011e+00,   3.00625000e+01,   2.21250000e+01,
         1.44375000e+01,              nan,   3.40625000e+00,
         2.17500000e+01,   1.93333333e+01,   1.74375000e+01,
                    nan,   1.98750000e+01,   8.04166667e+00,
         4.34567901e+00,              nan,              nan,
                    nan,              nan,   1.16875000e+01,
                    nan,   2.48750000e+01,   1.95000000e+01,
                    nan,   1.43125000e+01,   1.95000000e+01,
         2.62500000e+01,   2.13750000e+01,   1.87500000e+01,
         5.92592593e+00,   2.00000000e+01,   2.25000000e+01,
                    nan,   3.61250000e+01,              nan,
         1.29375000e+01,   8.70833333e+00,   9.40625000e+00,
         2.71250000e+01,   1.95000000e+01,   1.50000000e+00,
                    nan,   1.08750000e+01,   5.65625000e+00,
                    nan,   5.58024691e+00,   1.96000000e+02,
         7.18750000e+00,   1.03333333e+01,              nan,
         1.08125000e+01,   3.15000000e+01,   3.24375000e+01,
         1.51875000e+01,              nan,   1.04375000e+01,
         3.53750000e+01,   2.10000000e+01,   1.31250000e+01,
         2.94375000e+01,              nan,   2.99583333e-02,
         2.42916667e+01,   1.53600393e+01,              nan,
                    nan,              nan,   2.36250000e+01,
         1.00000000e+01,   1.17424242e+01,   5.25781250e+00,
         1.42615492e+02,   4.58750000e+01,   1.69000000e+01,
                    nan,   2.38125000e+01,   2.70833333e+01,
         1.94444444e+00,   2.31875000e+01,   1.10312500e+01,
         2.17500000e+01,   2.94673540e+01,              nan,
         5.65625000e+00,   1.68750000e+01,   8.44444444e+00,
         2.67500000e+02,   1.57500000e+01,   4.47619048e+00,
         6.90625000e+00,   4.37500000e+00,   5.93750000e+01,
         1.49375000e+01,   3.25000000e+01,              nan,
         3.81250000e+00,   3.87500000e+00,   1.92500000e+01,
         4.27500000e+01,   5.81250000e+01,   3.91666667e+00,
                    nan,   6.93750000e+00,   2.81250000e+01,
         1.72500000e+01,   2.04166667e+01,   2.46093750e+00,
         1.60000000e+01,   3.81250000e+01,              nan,
         1.47500000e+01,   2.61875000e+01,              nan,
         1.94380000e+01,              nan,   4.76562500e+01,
         2.24166667e+01,   1.15000000e+02,   1.27500000e+01,
                    nan,   9.75000000e+00,   1.21875000e+01,
                    nan,   1.03750000e+01,   2.42500000e+01,
                    nan,   6.68750000e+00,   4.18750000e+01,
         1.13750000e+01,   1.00000000e+01,   3.47500000e+01,
                    nan,   1.61666667e+01,   1.33750000e+01,
         1.24057906e+01,   4.75000000e+00,   7.28125000e+00,
         3.38750000e+01,   2.83057851e+01,   2.63888889e+00,
         3.37500000e+00,   1.46250000e+01,   1.15625000e+01,
                    nan,   1.81250000e+01,   4.18104243e+00,
         2.15167549e+00,              nan,   1.88125000e+01,
         2.80000000e+01,   4.81481481e+00,   2.85000000e+01,
         4.30000000e+01,              nan,   7.18750000e+00,
                    nan,              nan,   2.80625000e+01,
         3.79166667e+00,   2.53750000e+01,   9.87500000e+00,
         1.46875000e+01,   2.40625000e+01,   1.28125000e+01,
         7.43750000e+00,              nan,   1.77500000e+01,
         2.63750000e+01,   3.16250000e+01,   3.16666667e+00,
         1.69259259e+01,   1.69750000e+01,   1.31666667e+01,
         3.54687500e+00,              nan,   8.93750000e+00,
         3.61223118e+01,   2.15000000e+01,              nan,
         3.64062500e+00,   4.96250000e+01,   2.70000000e+01,
         1.13750000e+01,   2.51724138e+01,   2.32500000e+01,
         2.03750000e+01,   2.07500000e+01,   9.68750000e+00,
         1.12500000e+01,              nan,   1.57500000e+01,
         6.43750000e+00,              nan,   2.75781250e+01,
                    nan,   1.50000000e+01,              nan,
         3.61250000e+01,              nan,              nan,
         1.29166667e+01,              nan,   1.21875000e+01,
         2.00000000e+01,   4.87500000e+01,              nan,
         4.05000000e+01,   1.58206250e+00,              nan,
                    nan,   2.96875000e-01,              nan,
         2.53750000e+01,   1.18750000e+01,              nan,
         1.63333333e+01,   2.87500000e+00,   3.38750000e+01,
         1.22500000e+01,   7.50000000e+00,              nan,
         1.76250000e+01,   6.12500000e+00,   1.45796209e+01,
         3.60416667e+00,              nan,   2.07261292e+01,
         3.65432099e+00,              nan,              nan,
         4.88750000e+01,              nan,   2.86250000e+01,
         1.94583333e+01,   4.48750000e+01,   8.06250000e+00,
         3.47656250e-01,   5.41666667e+00,   1.08385839e+02,
                    nan,   1.16250000e+01,   3.85625000e+01,
         4.66666667e+00,   1.80000000e+01,              nan,
                    nan,   5.57500000e+01,   2.91875000e+01,
         1.15277778e+01,   1.34973005e+01,              nan,
                    nan,   4.72424873e+00,   9.25781250e-01,
         2.26250000e+01,   2.75925926e+00,   1.40625000e+01,
                    nan,   1.10000000e+01,   1.84375000e+01,
         9.56250000e+00,   1.01250000e+01,   9.90625000e+00,
                    nan,   1.83750000e+01,   1.15625000e+01,
         4.16666667e+00,   4.59375000e+00,   2.39392657e+01,
         1.70000000e+01,   1.82500000e+01,   1.62187500e+01,
                    nan,   3.87500000e+00,   3.90000000e+01,
         2.34166667e+01,              nan,              nan,
         1.41250000e+01,   3.27500000e+01,   4.53744037e+01,
         2.20000000e+01,   7.25000000e+00,   2.52500000e+01,
         2.48750000e+01,   9.29687500e+00,   3.82720114e+00,
         1.32500000e+01,   2.64261144e+01,              nan,
         1.67907966e+01,   1.07500000e+01,   4.79976001e+01,
         2.85625000e+01,   7.47916667e+00,   7.43750000e+00,
         8.43750000e+00,              nan,   5.37500000e+00,
         1.96666667e+01,   1.56875000e+01,              nan,
         1.00630032e+02,   2.00625000e+01,   4.54166667e+00,
         1.89062500e+00,   9.15625000e+00,   1.54375000e+02,
         4.84375000e+00,   2.86725000e+00,   6.78125000e+00,
         2.24375000e+01,   1.69166667e+02,   2.95000000e+01,
         8.50000000e+00,              nan,              nan,
         1.38750000e+01,   2.18750000e+01,   1.52500000e+01,
                    nan,   2.40000000e+02,   1.34375000e+01,
         3.00000000e+00,   2.67500000e+01,   6.03125000e+00,
         4.40000000e+01,   1.21250000e+01,              nan,
         4.04687500e+00,   2.17500000e+01,   8.20312500e-01,
         2.10625000e+01,   8.18750000e+00,   2.32500000e+01,
         8.80555556e+00,   2.42500000e+01,   3.33750000e+01,
         1.17916667e+01,              nan,              nan,
         4.50000000e+00,              nan,   3.88125000e+01,
         1.19925000e+00,              nan,   1.45000000e+01,
         4.75000000e+00,   9.12500000e+00,              nan,
                    nan,   3.23439521e+00,   1.98125000e+01,
         7.56250000e+00,   1.50000000e+01,   1.75000000e+01,
         2.70625000e+01,              nan,              nan,
         2.73750000e+01,   1.42500000e+01,   2.21250000e+01,
         3.45312500e+00,   1.06250000e+02,              nan,
         1.18649842e+01,   4.73437500e+00,   2.20625000e+01,
         1.35937500e+01,   1.80000000e+01,              nan,
                    nan,   1.12893750e+00,              nan,
         4.86111111e+00,   1.44166667e+01,   2.43750000e+01,
         2.65000000e+01,   3.10000000e+01,   2.05000000e+01,
         2.96250000e+01,   9.68750000e+00,              nan,
         1.31562500e+01,              nan,   6.59375000e+00,
                    nan,   5.18750000e+00,   5.31250000e+00,
         1.84166667e+01,   1.70000000e+01,   2.97500000e+01,
                    nan,              nan,   1.27572016e+00,
         7.87500000e+00,              nan,   2.25000000e+01,
         2.77500000e+01,   4.48750000e+01,   1.01666667e+01,
         1.30000000e+01,              nan,   3.75000000e+01,
         2.43125000e+01,   5.90625000e+00,   9.12500000e+00,
         1.43125000e+01,   1.72500000e+01,   7.12500000e+00,
         1.79687500e+00,   2.26562500e+00,   5.73750000e+01,
                    nan,              nan,   1.38125000e+01,
         4.75000000e+00,   2.49375000e+01,   2.16567914e+01,
                    nan,   1.47500000e+01,   1.11666667e+01,
         1.23750000e+01,   2.01250000e+01,              nan,
         7.21590909e+00,   1.77000000e+01,   4.36250000e+01,
         1.84687500e+01,              nan,              nan,
         3.35000000e+01,              nan,   2.33125000e+01,
         2.33125000e+01,   7.15625000e+00,   1.78125000e+01,
         6.00000000e+00,   7.64166667e+01,   1.13777778e+00,
                    nan,              nan,   1.87500000e+05,
                    nan,              nan,   7.75000000e+00,
         1.10625000e+01,   2.02500000e+01])

In [130]:
j=0
i = tradedate[j]
cap = portfolio.loc[0, i]
balance_cash[i] = cap * balance_weight[i]
balance_share[i] = list(np.array(balance_cash[i])
                                  / np.array(balance_price[i]))
balance_share[i] = balance_share[i].fillna(0)
balance_share[i] = balance_share[i].astype(int)
a = balance_price_full[tradedate_full[j+1]].fillna(0)

In [132]:
np.dot(balance_share[i], a)

1188173.8504709415

In [125]:
portfolio

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601,20170901
0,1000000,1.18817e+06,1.22976e+06,1.32423e+06,1.48105e+06,1.49217e+06,1.60959e+06,1.69008e+06,1.88348e+06,2.1706e+06,...,1.07559e+07,9.68583e+06,9.92981e+06,9.57819e+06,1.06657e+07,1.11671e+07,1.04759e+07,1.10365e+07,1.1081e+07,10991700.9

In [133]:
# equally weighted portfolio:
for j in range(len(tradedate)):
    i = tradedate[j]
    cap = portfolio_equal.loc[0, i]
    balance_cash_equal[i] = cap * equal_weight[i]
    balance_share_equal[i] = list(np.array(balance_cash_equal[i])
                                  / np.array(balance_price[i]))
    balance_share_equal[i] = balance_share_equal[i].fillna(0)
    balance_share_equal[i] = balance_share_equal[i].astype(int)
    a = balance_price_full[tradedate_full[j+1]].fillna(0)
    portfolio_equal.loc[0, tradedate_full[j+1]] = np.dot(balance_share_equal[i], a)

'''
i = tradedate[j+1]
cap = portfolio_equal.loc[0, i]
balance_cash_equal[i] = cap * equal_weight[i]
balance_share_equal[i] = list(np.array(balance_cash_equal[i])
                                  / np.array(balance_price[i]))
balance_share_equal[i] = balance_share_equal[i].fillna(0)
balance_share_equal[i] = balance_share_equal[i].astype(int)
'''

balance_cost_equal = np.diff(balance_share_equal, axis = 1)
balance_cost_equal = balance_cost_equal * balance_price
balance_cost_equal = np.sum(balance_cost_equal, axis = 0) * transaction_percent
balance_cost_equal['20170901'] = 0

In [134]:
portfolio_equal

,19950601,19950901,19951201,19960301,19960603,19960903,19961202,19970303,19970602,19970902,...,20150601,20150901,20151201,20160301,20160601,20160901,20161201,20170301,20170601,20170901
0,1000000,1.11198e+06,1.15874e+06,1.22075e+06,1.34822e+06,1.30972e+06,1.47648e+06,1.50854e+06,1.66874e+06,1.86372e+06,...,1.94856e+07,1.71599e+07,1.7803e+07,1.64405e+07,1.86475e+07,1.97285e+07,2.06791e+07,2.22835e+07,2.19655e+07,22138301.57